- enable_contrib: false
- enable_nonfree: false
- add_testing:
  - append_in:
    - /etc/apt/sources.list
    - |

      deb $${apt_repository} testing main

- add_contribs_and_nonfree_sources:
  - exec_in: |
      if [ $${enable_contrib} = true ]; then
        REPO_CONTRIB="contrib"
      fi
  - exec_in: |
      if [ $${enable_nonfree} = true ]; then
        REPO_NONFREE="non-free"
      fi
  - exec_in: perl -pi -e "s/testing main$/testing main $REPO_CONTRIB $REPO_NONFREE/" /etc/apt/sources.list

- make_it_not_optional:
  - write_in:
    - /etc/apt/apt.conf.d/00default-release
    - |
      APT::Default-Release "stable";

- update_repositories:
  # Deactivate the check to make the cache system works after a while...
  - exec_in: apt-get -o Acquire::Check-Valid-Until=false -y --force-yes update
